development:
  cloud_name: bm4l2f1pq
  api_key: "384786930741074"
  api_secret: "-LladYP3cuLWz1QM3o_wpofEaWI"
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: bm4l2f1pq
  api_key: "384786930741074"
  api_secret: "-LladYP3cuLWz1QM3o_wpofEaWI"
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: bm4l2f1pq
  api_key: "384786930741074"
  api_secret: "-LladYP3cuLWz1QM3o_wpofEaWI"
  enhance_image_tag: true
  static_file_support: false
